# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Kevin's Practical Embedded
email: shocktohp@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
    I am a software engineering senior at Auburn University, and am currently working in the IT department of Building Science.
		When I am not at work, I try to keep myself gainfully employed, either with hobbiest embedded systems projects, or by making things down at my forge.
		If you are interested in learning more about what I do, feel free to look at my blog, or the forge blog. I also have my CV linked for any employers who have happened across my site.
		Please enjoy your stay here and feel free to look around, I am happy to have you.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://kevinconyers.xyz/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ShockTohp
github_username:  KevinGConyers

# Build settings
markdown: kramdown
theme: jekyll-theme-clean-blog
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
