title: Kevin Conyers' Hobby Hub
description: >
        This is my personal blog where I talk about my various hobby projects. These include but are not limited too,
        Blacksmithing
        Embedded Systems Projects
        Other Coding Projects
        
        So have fun and take a look around!
google_analytics:
theme: jekyll-theme-midnight
home: https://kevinconyers.xyz
about: https://kevinconyers.xyz/about
base_url: /blogs/
